// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type BlogId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogId) Reset()         { *m = BlogId{} }
func (m *BlogId) String() string { return proto.CompactTextString(m) }
func (*BlogId) ProtoMessage()    {}
func (*BlogId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

func (m *BlogId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogId.Unmarshal(m, b)
}
func (m *BlogId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogId.Marshal(b, m, deterministic)
}
func (m *BlogId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogId.Merge(m, src)
}
func (m *BlogId) XXX_Size() int {
	return xxx_messageInfo_BlogId.Size(m)
}
func (m *BlogId) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogId.DiscardUnknown(m)
}

var xxx_messageInfo_BlogId proto.InternalMessageInfo

func (m *BlogId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BlogList struct {
	Blogs                []*Blog  `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogList) Reset()         { *m = BlogList{} }
func (m *BlogList) String() string { return proto.CompactTextString(m) }
func (*BlogList) ProtoMessage()    {}
func (*BlogList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}

func (m *BlogList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogList.Unmarshal(m, b)
}
func (m *BlogList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogList.Marshal(b, m, deterministic)
}
func (m *BlogList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogList.Merge(m, src)
}
func (m *BlogList) XXX_Size() int {
	return xxx_messageInfo_BlogList.Size(m)
}
func (m *BlogList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogList.DiscardUnknown(m)
}

var xxx_messageInfo_BlogList proto.InternalMessageInfo

func (m *BlogList) GetBlogs() []*Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "models.Blog")
	proto.RegisterType((*BlogId)(nil), "models.BlogId")
	proto.RegisterType((*BlogList)(nil), "models.BlogList")
}

func init() {
	proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1)
}

var fileDescriptor_6745b25902462fb1 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x77, 0xb7, 0xdd, 0xa5, 0x4e, 0x45, 0x64, 0x10, 0x09, 0xf1, 0x52, 0x72, 0xea, 0xc5,
	0x14, 0xaa, 0x78, 0x96, 0x82, 0x87, 0x82, 0xa7, 0xfe, 0x03, 0x63, 0x62, 0x08, 0xa4, 0x4c, 0x69,
	0xe2, 0x61, 0xff, 0x8f, 0x3f, 0x54, 0x26, 0x51, 0x68, 0x05, 0x6f, 0x33, 0x6f, 0x5e, 0xde, 0xfb,
	0x08, 0x80, 0x89, 0xe4, 0xf5, 0xe1, 0x48, 0x99, 0x70, 0xd8, 0x93, 0x75, 0x31, 0xc9, 0x3b, 0x4f,
	0xe4, 0xa3, 0x5b, 0x15, 0xd5, 0x7c, 0x7e, 0xac, 0xdc, 0xfe, 0x90, 0xc7, 0x6a, 0x52, 0xcf, 0x30,
	0xdd, 0x44, 0xf2, 0x78, 0x05, 0x5d, 0xb0, 0xa2, 0x5d, 0xb4, 0xcb, 0x8b, 0x5d, 0x17, 0x2c, 0xde,
	0x40, 0x9f, 0x43, 0x8e, 0x4e, 0x74, 0x45, 0xaa, 0x0b, 0x22, 0x4c, 0x0d, 0xd9, 0x51, 0x4c, 0x8a,
	0x58, 0x66, 0x25, 0x60, 0xe0, 0x84, 0xad, 0xfd, 0x9b, 0xa1, 0x34, 0xcc, 0xf8, 0xf2, 0x1a, 0x52,
	0x46, 0x05, 0x3d, 0xa3, 0x25, 0xd1, 0x2e, 0x26, 0xcb, 0xf9, 0xfa, 0x52, 0x57, 0x38, 0xcd, 0x86,
	0x5d, 0x3d, 0xad, 0xbf, 0x5a, 0xe8, 0x79, 0x4f, 0xf8, 0x04, 0x33, 0xef, 0x72, 0x9d, 0x6f, 0x75,
	0xe5, 0xd7, 0xbf, 0xfc, 0xfa, 0x85, 0xf9, 0xe5, 0xf5, 0x69, 0x04, 0x77, 0xa8, 0x06, 0xef, 0x61,
	0xfe, 0xf3, 0x6e, 0x33, 0x32, 0xd0, 0xa9, 0x65, 0x6b, 0xe5, 0x59, 0xab, 0x6a, 0xf0, 0x11, 0xe0,
	0xfd, 0xe8, 0xde, 0xb2, 0x2b, 0x5f, 0x70, 0x76, 0x95, 0xff, 0xd4, 0xaa, 0xc6, 0x0c, 0x45, 0x79,
	0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6d, 0xf4, 0x30, 0x6c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogsClient is the client API for Blogs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogsClient interface {
	GetBlogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BlogList, error)
	GetBlogById(ctx context.Context, in *BlogId, opts ...grpc.CallOption) (*Blog, error)
	CreateBlog(ctx context.Context, in *Blog, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type blogsClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogsClient(cc grpc.ClientConnInterface) BlogsClient {
	return &blogsClient{cc}
}

func (c *blogsClient) GetBlogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BlogList, error) {
	out := new(BlogList)
	err := c.cc.Invoke(ctx, "/models.Blogs/getBlogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) GetBlogById(ctx context.Context, in *BlogId, opts ...grpc.CallOption) (*Blog, error) {
	out := new(Blog)
	err := c.cc.Invoke(ctx, "/models.Blogs/getBlogById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogsClient) CreateBlog(ctx context.Context, in *Blog, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/models.Blogs/createBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogsServer is the server API for Blogs service.
type BlogsServer interface {
	GetBlogs(context.Context, *emptypb.Empty) (*BlogList, error)
	GetBlogById(context.Context, *BlogId) (*Blog, error)
	CreateBlog(context.Context, *Blog) (*emptypb.Empty, error)
}

// UnimplementedBlogsServer can be embedded to have forward compatible implementations.
type UnimplementedBlogsServer struct {
}

func (*UnimplementedBlogsServer) GetBlogs(ctx context.Context, req *emptypb.Empty) (*BlogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogs not implemented")
}
func (*UnimplementedBlogsServer) GetBlogById(ctx context.Context, req *BlogId) (*Blog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogById not implemented")
}
func (*UnimplementedBlogsServer) CreateBlog(ctx context.Context, req *Blog) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlog not implemented")
}

func RegisterBlogsServer(s *grpc.Server, srv BlogsServer) {
	s.RegisterService(&_Blogs_serviceDesc, srv)
}

func _Blogs_GetBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).GetBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Blogs/GetBlogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).GetBlogs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_GetBlogById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).GetBlogById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Blogs/GetBlogById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).GetBlogById(ctx, req.(*BlogId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blogs_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogsServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.Blogs/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogsServer).CreateBlog(ctx, req.(*Blog))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blogs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.Blogs",
	HandlerType: (*BlogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getBlogs",
			Handler:    _Blogs_GetBlogs_Handler,
		},
		{
			MethodName: "getBlogById",
			Handler:    _Blogs_GetBlogById_Handler,
		},
		{
			MethodName: "createBlog",
			Handler:    _Blogs_CreateBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}
